[tools]
python = "3.14"
ruff = "0.15.9"
uv = "0.11.3"

[tasks.sync]
run = "uv sync --frozen --extra dev"

[tasks.venv]
run = "uv venv .venv --allow-existing --seed"

[tasks.install]
depends = ["sync"]

[tasks.lint]
depends = ["install"]
run = ".venv/bin/ruff check ."

[tasks.test]
depends = ["install"]
run = ".venv/bin/pyrefly check --summarize-errors && .venv/bin/python -m pytest -vv"

[tasks.format]
depends = ["install"]
run = ".venv/bin/ruff format"

[tasks.dev]
depends = ["install"]
run = "uv run fastapi dev"
