[project]
name = "dddpy"
version = "0.10.0"
description = "An example of Python FastAPI Domain-Driven Design and Onion Architecture."
authors = [{ name = "iktakahiro", email = "takahiro.ikeuchi@gmail.com" }]
dependencies = [
    "sqlalchemy==2.0.9",
    "pydantic==2.8.2",
    "fastapi==0.111.1",
    "uvicorn==0.30.3",
    "shortuuid==1.0.13",
]
readme = "README.md"
requires-python = ">=3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "mypy>=1.11.0",
    "pytest>=8.3.2",
    "ruff>=0.5.5",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["dddpy"]

[tool.ruff]
line-length = 88
indent-width = 4

target-version = "py312"

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

fixable = ["ALL"]
unfixable = []

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

 # Allow unused variables when underscore-prefixed.
 dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"