[project]
name = "dddpy"
version = "0.10.0"
description = "An example of Python FastAPI Domain-Driven Design and Onion Architecture."
authors = [{ name = "iktakahiro", email = "takahiro.ikeuchi@gmail.com" }]
dependencies = [
    "sqlalchemy==2.0.9",
    "pydantic==2.8.2",
    "fastapi==0.111.1",
    "uvicorn==0.30.3",
    "shortuuid==1.0.13",
]
readme = "README.md"
requires-python = ">=3.12"

[project.optional-dependencies]
dev = ["mypy>=1.11.0", "pytest>=8.3.2", "ruff>=0.5.5"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["dddpy"]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"

# Lint configuration
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
