[tool.poetry]
name = "dddpy"
version = "0.9.0"
description = "Python DDD example using FastAPI"
authors = ["iktakahiro <takahiro.ikeuchi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = "^1.4.41"
pydantic = "^1.10.2"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
shortuuid = "^1.0.9"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
mypy = "^0.981"
pytest = "^7.1.3"
isort = "^5.10.1"
pylint = "^2.15.3"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
