[tool.poetry]
name = "dddpy"
version = "0.9.0"
description = "An example of Python FastAPI Domain-Driven Design and Onion Architecture."
authors = ["iktakahiro <takahiro.ikeuchi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "^2.0.9"
pydantic = "^1.10.7"
fastapi = "^0.95.1"
uvicorn = "^0.21.1"
shortuuid = "^1.0.11"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.2.0"
pytest = "^7.3.1"
isort = "^5.12.0"
pylint = "^2.17.2"

[build-system]
requires = ["poetry>=1.4.0"]
build-backend = "poetry.masonry.api"
